name: Build package, documentation, and test coverage

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/hoopmanagerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: VitorSuperUser@@20
      SERVER_PORT: 8081
      TOKEN_SECRET_KEY: 563bdb82034470d3a7dd21676545e3c0cbfa4b297cb2ca7024f2bdf70742378b
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean package
      - name: Generate Javadocs
        run: mvn javadoc:javadoc
      - name: Run tests with coverage
        run: mvn test jacoco:report
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-build
          path: target/*.jar
      - name: Upload Javadoc artifact
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/site/apidocs
      - name: Upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: target/site/jacoco
