name: Build package, documentation, and test coverage

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean package
      - name: Generate Javadocs
        run: mvn javadoc:javadoc
      - name: Run tests with coverage
        run: mvn test jacoco:report
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-build
          path: target/*.jar
      - name: Upload Javadoc artifact
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/site/apidocs
      - name: Upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: target/site/jacoco
